drop table CDW_SAPP_D_BRANCH;
drop table external_CDW_SAPP_BRANCH;
Create external table external_CDW_SAPP_BRANCH(
BRANCH_CODE int,
BRANCH_NAME string,
BRANCH_STREET string,
BRANCH_CITY string,
BRANCH_STATE string,
BRANCH_ZIP int,
BRANCH_PHONE string,
LAST_UPDATED timestamp
)
row format delimited fields terminated by ','
stored as textfile location  "/user/maria_dev/Credit_Card_System/CDW_SAPP_BRANCH";



