drop table CDW_SAPP_F_CREDIT_CARD;
drop table external_CDW_SAPP_CREDITCARD;
Create external table external_CDW_SAPP_CREDITCARD(
TRANSACTION_ID string,
CUST_CC_NO string,
TIMEID string,
CUST_SSN int,
BRANCH_CODE int,
TRANSACTION_TYPE string,
TRANSACTION_VALUE decimal
)
row format delimited fields terminated by ','
stored as textfile location  "/user/maria_dev/Credit_Card_System/CDW_SAPP_CREDITCARD";









